### ISSUE TITLE
Match packages based on gentoo package atoms

### ISSUE THREAD

**Issue by haasn** [vaeth/eix#11]
**eix** should be able to search for packages by using the same syntax as eg. **emerge** uses. Examples:

I would expect this command to print a list of all installed packages that have the version 9999:
`eix -I '*/*-9999'`

I would expect this command to print a list of all installed packages from the overlay haskell:
`eix -I '*/*::haskell'`

In both cases, I simply get no matches. I'm aware that there are some work-arounds for some of these queries, eg. `eix --installed-from-overlay haskell`, but other times I have to come up with dirty hacks like `eix '-I*' --format '<installedversions:NAMEVERSION>' | grep 9999` to get the same functionality.

It would be so much more consistent, easier to remember and less of a headache in general if I could use portage-style syntax.

**Comment by vaeth** [comment]
The first test should perhaps be eix -I --in-overlay haskell
However, searching for version numbers makes no sense. Indeed, you are actually not looking for version numbers but for the "live" property; for instance also 9999999 is a number which is sometimes used for this, and, moreover, this property is actually independent of the version number.
This property is inofficially marked as PROPERTIES="live" and can be checked with eix --properties-live. Unfortunately, most ebuild do not properly mark this inofficial feature. Complain about the corresponding ebuild others and the pms crazyness to not include such a property officially due to bikesheddding for many years.
In any case, building support for searching for version numbers in eix only to work around a missing pms feature would be the wrong way: Searching for version numbers really makes no sense when you think about it...

**Comment by haasn** [comment]
I would tend to agree with your approach that this is due to good technical distinctions, my complaint here is mainly that I always find myself reading the very long man page of eix every time I want to accomplish something like this - it's not very intuitive, and my first instinct is always to try portage's syntax.

But I suppose I can concede that argument as an unfortunate side effect of them simply not being the same tool. It's just unfortunate.

**Comment by vaeth** [comment]
Closing, since there is not much I can reasonably do about. CANTFIX
