### ISSUE TITLE
Package.mask "a wildcard is only valid as the last symbol" error as of 0.31.6

### ISSUE THREAD

**Issue by shiznix** [vaeth/eix#21]
Hi,

Getting an error after upgrading from 0.31.4 to 0.31.6 that states:
-- invalid line 21 in /etc/portage/package.mask: "=gnome-\*/\*-\*18\*::gentoo"
    a wildcard is only valid as the last symbol

The syntax however is valid and works fine with <=eix-0.31.4

'man portage' "Wildcard Patterns" also verifies the syntax to be ok in the 'Examples' section:
\# package.mask to prevent emerge --autounmask from selecting live ebuilds
=\*/\*-\*9999\*

Thanks :)

**Comment by vaeth** [comment]
This does not follow pms, and it is really not clear what it should mean.
I opened a corresponding portage bug:
https://bugs.gentoo.org/show_bug.cgi?id=572178

**Comment by vaeth** [comment]
Since there was no reaction on the bug on gentoo, I reintroduced "extended version globbing" (which is what previous eix versions did in such a case): If * occurs not at the last symbol in something which looks like a version with =, then string globbing against a canonical presentation of the version is made.
I don't consider this a perfect solution, but it seems (essentially) to match portage's current behaviour.

Closing since the new implementation is now in eix-0.31.7

**Comment by shiznix** [comment]
Many thanks :)
