### ISSUE TITLE
eix-test-obsolete doesn't seem to consult use.stable.mask

### ISSUE THREAD

**Issue by orlitzky** [vaeth/eix#34]
Background:

There are a few cases in the tree (php, python, ruby, etc.) where a `USE_EXPAND` variable pulls in different major versions of things. With PHP, the new php-7.x slots are a major change over the old 5.x ones, and not everything is compatible with 7.x yet. We want to _support_ php-7.x if possible -- even in stable packages -- but we don't want stable users to be able to set `PHP_TARGETS=php7-0` and have it try to pull in the unstable `php:7.0` on a stable system. In other words, this follows the usual policy of not allowing unstable packages to be pulled in by stable ones conditional on some `USE` flag.

The way we've prevented that situation is to add `php_targets_php7-0` and `php_targets_php7-1` to `profiles/base/use.stable.mask`. Other languages have done the same.

The problem:

The flags in `use.stable.mask` are masked even if the dependency that it would pull in has been added to `package.accept_keywords`. On my machine, I've got `dev-lang/php:7.0 ~amd64` allowed and `PHP_TARGETS=php7-0`. Now two things can happen:

1. By default, if I try to emerge `dev-php/pecl-geoip`, the `php_targets_php7-0` flag is masked, so it looks like I've selected **no** PHP implementations, and portage bails because `REQUIRED_USE` is not satisfied.

2. If I add `dev-php/pecl-geoip ~amd64` to my `package.accept_keywords`, then the `use.stable.mask` no longer applies, and I can proceed normally. But `dev-php/pecl-geoip-1.1.1-r2` is a stable package!

In the second case, eix-test-obsolete will tell me that having `=dev-php/pecl-geoip-1.1.1-r2 ~amd64` in my `package.accept_keywords` is redundant. However, if I remove it, the installed version has unsatisfied dependencies, because `use.stable.mask` is applied and it looks like I have no `PHP_TARGETS`. So, it isn't redundant =)

Fixing it:

Of course, eix-test-obsolete is going to have the same problem that portage does: it can't go digging through ebuilds trying to figure out which packages would get pulled in by every stable-masked USE flag in order to check for those packages in `package.accept_keywords`. But it could at least cross-reference the flags in the "redundantly" keyworded ebuild and `use.stable.mask`, and maybe output a warning or explanation of why that entry _might_ not be redundant.

Whether or not this edge case is worth it depends on how hard it would be to implement the cross-referencing.

**Comment by vaeth** [comment]
I am aware about the problem, but the real cause is that unmasking unmasked package is a workaround for a workaround of a broken concept which was only introduced to workaround repoman's insufficiencies. I think that you should not use this broken concept, as there are alternatives (see below).

Technically, eix is not prepared to deal with this workaround-workaround "automatically" for 2 reasons:

1. Although the intention of "redundant" is sometimes intuitive, people have varying ideas about it. It is very precisely specified in eix what "redundant" actually means (depending on your configuration e.g. that a package is unmasked although no unmasked version is installed). This is already a very fragile definition and not everybody will agree with it if you think about multiple slots, unmasking various noninstalled versions in various lines, etc. To burden this definition with even more "magic" is not appropriate (and also hardly possible in the eix REDUNDANT_IF-*-interface).
2. eix has no infrastructure at all to work with USE-flags. Only the simplest things - values of IUSE and the values stored in /var/db - are dealt with in a very simple manner.

As a workaround, you have to specify the exception manually. Essentially there are 2 ways:

1. Make use of /etc/portage/package.nowarn (e.g. add the line ```dev-php/pecl-geoip no_change```).
2. Remove the keyword from use.stable.mask in your local profile (e.g. add the line ```-php_targets_php-7.1``` to /etc/portage/profile/use.stable.mask).

In my opinion, the second alternative is the correct solution, anyway: You want to unmask the USE-flag, not to unmask the package with the USE-flag, so you should explicitly do this and not use some hack which has the former only as a side effect.
(I have not tried, but perhaps you can also unmask the use-flags for a specific package only by using package.use.stable.mask if you do not want to unmask it globally. But I would say even unmasking it globally is the correct way when you actually have installed php-7.1)
I actually use a similar entry currently to run python-3.5 instead of python-3.4 on a mainly stable system.

**Comment by orlitzky** [comment]
> As a workaround, you have to specify the exception manually. Essentially there are 2 ways:
> 
>  ...
>  2. Remove the keyword from use.stable.mask in your local profile (e.g. add the line -php_targets_php-7.1 to /etc/portage/profile/use.stable.mask).

Thanks, this is the best solution and it hadn't even occurred to me. Problem solved!
