### ISSUE TITLE
-std=c++11 is now mandatory

### ISSUE THREAD

**Issue by xmw** [vaeth/eix#35]
Gentoo ebuild enforces CXXFLAGS by using --disable-new_dialect, the resulting CXXFLAGS misses -std=c++11 and subsequent build fails with

`In file included from cache/common/assign_reader.cc:10:0:                        
./cache/common/assign_reader.h:43:72: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11
   ATTRIBUTE_NONNULL_ const char *get_md5sum(const std::string &filename) OVERRIDE;`

I've added `inherit flag-o-matic` and `append-cxxflags -std=c++11` for the 0.32.5 version bump, but I think it could be hardcoded into the configure.ac

Thanks

**Comment by vaeth** [comment]
No, -std=c++11 is not necessary; please remove this from the ebuild again.

More verbose explanation:

The above is only a warning and not an error. In fact, the configure.ac checks whether the compiler gives an error for "override" and does not use it in that case. (So, e.g. even if the user should have -Werror in his CXXFLAGS.

Please remove that -std=c++11 again, because it violates gentoo's "QA" policy which is to mangle CXXFLAGS only if the compilation fails without this. Indeed, I had a lengthy discussion with mgorny about his removal of all the flags which ensure that the produced binary is fast, small, and secure, but he insisted that gentoo QA policy for ebuilds in the tree be very clear:

Even if the prduced code is completely inefficient, long, and insecure and upstream strongly recommends certain CXXFLAGS to avoid this, ebuilds in the tree should ignore upstream and not add these flags and even patch the build system to avoid adding it as long as the code compiles without it. IMHO, this is an insane policy, because it forces the user to look up upstream's recommendation for every single package and add CXXFALGS on a per-package basis manually if he wants to have sane binaries, but mgorny patched it all out it despite my protest. That's why I continue to offer a sane ebuild in the mv overlay outside of the tree without this crippling of the configure options.

**Comment by xmw** [comment]
Hmm, maybe we shoud set `CXXFLAGS=${CFLAGS} -std=c++17` in `make.conf`

But I acidentlly picked out the wrong line, the whole output w/o -std=c++11 is 

' x86_64-pc-linux-gnu-g++ -DHAVE_CONFIG_H -I. -I..    -DSYSCONFDIR=\"/etc\" -DLOCALEDIR=\"/usr/share/locale\"  -O2 -pipe -march=native --param l2-cache-size=8192 -c -o cache/common/assign_reader.o cache/common/assign_reader.cc
In file included from cache/common/assign_reader.cc:10:0:
./cache/common/assign_reader.h:43:72: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11
   ATTRIBUTE_NONNULL_ const char *get_md5sum(const std::string &filename) OVERRIDE;
                                                                        ^
./cache/common/assign_reader.h:44:75: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11
   ATTRIBUTE_NONNULL_ bool get_mtime(time_t *t, const std::string &filename) OVERRIDE;
                                                                           ^
In file included from cache/common/assign_reader.cc:10:0:
./cache/common/assign_reader.h:45:250: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11
   ATTRIBUTE_NONNULL_ void get_keywords_slot_iuse_restrict(const std::string& filename, std::string *eapi, std::string *keywords, std::string *slotname, std::string *iuse, std::string *required_use, std::string *restr, std::string *props, Depend *dep) OVERRIDE;
                                                                                                                                                                                                                                                          ^
./cache/common/assign_reader.h:46:78: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11
   ATTRIBUTE_NONNULL_ void read_file(const std::string& filename, Package *pkg) OVERRIDE;
                                                                              ^
cache/common/assign_reader.cc: In member function ‘bool AssignReader::get_map(const string&)’:
cache/common/assign_reader.cc:47:18: error: no matching function for call to ‘std::basic_ifstream<char>::basic_ifstream(const string&)’
  ifstream is(file);
                  ^
In file included from cache/common/assign_reader.cc:17:0:
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/fstream:495:7: note: candidate: std::basic_ifstream<_CharT, _Traits>::basic_ifstream(const char*, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::ios_base::openmode = std::_Ios_Openmode]
       basic_ifstream(const char* __s, ios_base::openmode __mode = ios_base::in)
       ^
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/fstream:495:7: note:   no known conversion for argument 1 from ‘const string {aka const std::__cxx11::basic_string<char>}’ to ‘const char*’
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/fstream:481:7: note: candidate: std::basic_ifstream<_CharT, _Traits>::basic_ifstream() [with _CharT = char; _Traits = std::char_traits<char>]
       basic_ifstream() : __istream_type(), _M_filebuf()
       ^
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/fstream:481:7: note:   candidate expects 0 arguments, 1 provided
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/fstream:455:11: note: candidate: std::basic_ifstream<char>::basic_ifstream(const std::basic_ifstream<char>&)
     class basic_ifstream : public basic_istream<_CharT, _Traits>
           ^
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/fstream:455:11: note:   no known conversion for argument 1 from ‘const string {aka const std::__cxx11::basic_string<char>}’ to ‘const std::basic_ifstream<char>&’
make[2]: *** [Makefile:1618: cache/common/assign_reader.o] Error 1
'

**Comment by pacho2** [comment]
Are you sure you are not allowed to set your upstream flags? Well, I remember many packages relying on "custom-flags" local USE flag to not follow upstream recommendations and allow people to use their flags (like mozilla products if I don't misremember)

**Comment by vaeth** [comment]
Thanks for reporting. This is of course a clear bug

Commit 58ce1aacd1524ad6fb988d9ebd2fa33d574803d5 should fix it.
The same commit should also "fix" the warning by doing the above mentioned tests with -Werror.

@pacho2: "custom-flags" means usually that the ebuild does not filter flags set by the user.

**Comment by vaeth** [comment]
Closing, since a version with the fix has been released. Reopen (or open another bug) if there are still compilation issues with some compiler versions
