### ISSUE TITLE
eix forces black text background on supported terminals

### ISSUE THREAD

**Issue by SharkWipf** [vaeth/eix#37]
See below: 
![image](https://cloud.githubusercontent.com/assets/751205/25139279/1debdb92-245d-11e7-9e70-3b7bcbc3ae00.png)  

Interestingly, running the same thing in tmux doesn't have this issue (although it seems to use less color here in general): 
![image](https://cloud.githubusercontent.com/assets/751205/25139367/4e7590aa-245d-11e7-93d8-09ce3157032d.png)

Tested in XFCE4-terminal with non-solid-black background, over SSH. I'd assume it'd reproduce in pretty much any terminal with a non-solid-black background though.

**Comment by vaeth** [comment]
What exactly is the bug?
I suggest that you read on the eix manpage the description of the variables TERM_ALT{1,2,3}, DARK, TERM_DARK, COLORFGBG_DARK and set it according to your needs.
If you think that some of the defaults is faulty, be precise, but be aware that the informations which eix can get "automatically" are limited to the TERM and COLORFGBG variables.

**Comment by vaeth** [comment]
I also recommend to read the section BUGS (and sort of FAQ) on the eix manpage

**Comment by SharkWipf** [comment]
Ah, didn't see those yet, I see. Thanks for the pointer.  
Setting BG0 - BG3 to none in `/etc/eixrc/00-eixrc` does remove the background color.  
Wouldn't it make more sense to have the background color default to none, though?  
This way it wouldn't have any issues out of the box with non-black/transparent terminals and should be pretty visible with most, if not all, color schemes by default.  
Besides, if a theme's configured for a black background, the background it's used on should already be black anyway, there shouldn't be a need to manually set it to black per-character.  
If a user does desire the black per-character background, they can still configure it, but I'd think most users (that don't have a pure-black background) would prefer not having the black per-character background or would sooner change their whole eix color scheme.

Or am I missing something obvious here?

**Comment by vaeth** [comment]
> and should be pretty visible with most, if not all, color schemes by default.

Unfortunately, this is not the case: It is not possible to produce a color scheme which uses about 100 of the 256 available colors (eix really makes use of a lot of colors to transport information) such that they all can be optically distinguished and such that most colors are visible (in the sense that they can be read) on most backgrounds. Moreover, there are a lot of terminals which have a very bright background and which do not set COLORFGBG at all, i.e. there are a lot of cases where the heuristics of eix is simply wrong.

When eix switched to 256 color output first, there were of lot of users complaining that at least the default should be such - no matter whether the heuristics succeeds - the output should be readable. The only reasonable way to get such a default (without using only 16 colors always by default) seems to force setting the background color.

Since the default cannot simultaneously be readable and beautiful and use 256 colors in all cases, and IMHO 16 colors is a very poor default for eix, I decided to exclude the second of these 3 conflicting goals.

**Comment by SharkWipf** [comment]
Hmm, fair enough, makes sense.  
Never realized eix really uses that many colors. I mean, I noticed it uses a lot of color (and it's lovely), but I never realized it used that many.  

In that case I can imagine it'd be pretty much impossible to find a color scheme that works well with everything, AFAIK the standard 16 colors automatically get inverted if they are the same color as the background, but I guess that won't work with 256 colors.  

That'd leave you with a choice between forcing users to change the theme themselves to get it usable or using a less-optimal-but-generic theme by default, i.e. by setting the background.  
Neither option is optimal, so I guess it makes sense compatibility wins then.  

Anyway, thanks for your explanation and pointing me to the solution.  
Eix is among the first things I install on any Gentoo box and it's one of the most useful Gentoo utilities IMO, so keep up the good work!
