### ISSUE TITLE
FR: distribute packageneedsme.sh script with eix?

### ISSUE THREAD

**Issue by jonasstein** [vaeth/eix#47]
Hi, regarding bug 
https://bugs.gentoo.org/637680 "app-portage/eix eix --maintainer-needed (or if not possible, in app-portage/gentoolkit equery)"

I have prepared a bash script packageneedsme.sh which prints all local installed packages needing a maintainer. I think it would be nice to add it to one of the existing packages perhaps to eix? What do you think? I think this feature will be very motivating for people to adopt maintainership, if they see that one of their loved packages is unmaintained. We would all benefit a lot from this little script.
https://github.com/jonasstein/packageneedsme

I am not sure what is the best way to distribute it now and promote it so that many people get motivated to adopt a package. Would you support to add this to the eix package? 
Or should it be a separate package?

**Comment by vaeth** [comment]
This does not really fit into eix's context.
In fact, it could easily be written to be completely independent of eix, using qlist or equery or directly accessing /var/db instead of eix -I (note that eix -I has some shortcomings for the intended purpose, anyway, see the comments on the eix manpage for that option).
Why don't you simply distribute your script as an independent package, perhaps even removing the dependency on eix? Note that eix is (in contrast to e.g. equery) not a gentoo project, so your chances for inclusion in the gentoo repository (e.g. if you suggest to proxy-maintain it) are higher if the script does not depend on eix.

**Comment by jonasstein** [comment]
OK, I was not aware of the shortcomings. I will have a look on a solution without eix then. Thank you.
