### ISSUE TITLE
Feature Request: don't discard entries for installed packages

### ISSUE THREAD

**Issue by Wyatts** [vaeth/eix#49]
Sometimes it happens: something you have installed gets removed from the tree.  Sure, it's a valid response to say "obviously, you should uninstall it", but that doesn't mean I don't want to use eix to grab the project address to see if they recommend an alternative (tightvnc) or just to get a better feel for what the package was (kenvy24) or check the installed version when it's likely you've just suffered a package move (gmic).

So it'd be nice if there were a way for eix to hang on to those entries until the package in question has been depclean'd.

**Comment by wwjjbb** [comment]
An installed package with an obsolete version also disappears from the eix database, although the eix output still shows the installation details of said package version. 

### Sequence ...

- Initial situation is that www-client/firefox-78.4.1 is installed and is the best version.

- Run "eix firefox" - the output  highlights version 78.4.1 in the "Available versions:" and shows the details in "Installed versions:"

- The eix database (xml/proto) contains 78.4.1 in the versions, and this has a populated Installed section

- Run emerge sync and eix-update

- www-client/firefox-78.4.1 is still installed, but it's no longer present in portage. There is a new version, 78.5.0, instead

- Run "eix" - the output shows 78.5.0 in the "Available versions:" but not 78.4.1 (fair enough, it's not available). **The details for 78.4.1 are still shown in "Installed versions:".**

- **The eix database doesn't contain an entry for 78.4.1** but does have the entry for 78.5.0 - so this info must be coming from the package db for the eix output.

- Upgrade firefox to 78.5.0, but do not run "eix-update". The eix database does not change, but the eix report does - it now shows the 78.5.0 installation details instead of the older version, which confirms this info is coming from the package db..

### Conclusion ...

The info that eix outputs for installed versions appears to be coming direct from the package database, rather than the eix database. This can cause subtle weirdness when they disagree, and also a lot of extra words in the man entry for "eix -I"  :-)

I do think that the installed but dead package versions, aka zombies, should be present in the eix database because they are there, they do affect dependencies, and it's important to know when they're there. 

I also think all of the --installed* flags should report the zombies like 'normal' packages but make them stand out in coloured output - do the whole entry in red? (i.e. there's a problem here!!).

**Comment by vaeth** [comment]
As I already that: This is not the way how eix works. There's a few information for installed packages which gets filled during the output and which can also be filtered during search, but it is not the main database which is searched.

There's the command -t to detect such lost packages. If you want to keep them, you should in any case put the ebuild into your local overlay, and then you will see them.

Won't fix.
