### ISSUE TITLE
Umlauts encoding problem? Väth written as V\"ath

### ISSUE THREAD

**Issue by sbraz** [vaeth/eix#51]
Hi, I noticed that in some files `Väth` is written as `V\"ath`, for instance:
https://github.com/vaeth/eix/blob/v0.33.3/Makefile.am#L7
I assume it has something to do with autotools since mostly `.in` and `.m4` files are affected.

This is certainly not the most serious bug but I was curious as to what caused this.

**Comment by vaeth** [comment]
This is intentional: All data which is eventually fed to a shell is kept pure ascii.
There might be some quite nonstandard shells in the wild which might stumble over non-ascii symbols.
So to be on the safe side, the TeX notation \"a is used instead of ä. Maybe it would have been better to do this for the .cc/.h files as well.

**Comment by sbraz** [comment]
Ah this makes sense :) Thanks for the info.
