### ISSUE TITLE
eix doesn't understand ::overlay [feature request]

### ISSUE THREAD

**Issue by Cyp** [vaeth/eix#55]
For consistency with emerge, eix should probably interpret
`eix -I 'dev-util/*::mrueg'`
as equivalent to
`eix -I --in-overlay mrueg 'dev-util/*'`
but currently the first command just says `No matches found`.

**Comment by vaeth** [comment]
The portage **version** syntax does not really make sense for eix in the mode for querying **packages**.
There is already too much magic guessing involved which confuses people regularly.

Where the portage syntax **does** make sense (and where it is actually essentially supported)
is in the --pipe mode where **versions** can be specified in the selection process. Try e.g.
```echo '>=app-shells/*-4.10:0::mv' |eix --pipe -I```

**Comment by Cyp** [comment]
Then I think
`echo '>=app-shells/*-4.10:0::mv' | eix --pipe -I`
does what I'd expect
`eix -I '>=app-shells/*-4.10:0::mv'`
or maybe
`eix -I -e '>=app-shells/*-4.10:0::mv'`
to do. Not sure what magic guessing goes on, but if it's not possible without any flags, then maybe a short flag to substitute `echo … | … --pipe` would be good. And possibly to say something like `I'm confused` instead of `No matches found` if typing something with any of `>`, `<`, `=`, `:`.

**Comment by vaeth** [comment]
> Not sure what magic guessing goes on

The string is used to "guess" your match field and match algorithm. The details depend on the configuration variables DEFAULT_MATCH_FIELD and DEFAULT_MATCH_ALGORITHM.
By the default settings when you search for ">=..." it is expected that you want to match against a DEPEND string. In contrast if you search for "../.." it is expected that you want to match against "category/package". If both applied, in the default settings the latter wins. You can add e.g. "^[<>=].*/ .error" at the beginning of DEFAULT_MATCH_FIELD to obtain an error message if your search string starts with e.g. < and contains /.

Since people might have configured these variables and expect a certain behaviour, I have no plans to change it.

Concerning the --pipe, I am not so sure whether it is so much an advantage: Having an option which adds a string stdin within --pipe argument would either require typing --pipe in addition or would cause again surprising behaviour (e.g. what happens in combination with/without --pipe etc.)
Most interactive shells provide simple enough means to use a more convenient syntax anyway,
e.g. in zsh or bash you can use
```eix --pipe <<<'app-shells/*::mv'```
