### ISSUE TITLE
eix-sync issue with source in make.conf with relative paths

### ISSUE THREAD

**Issue by wolfwood** [vaeth/eix#57]
`/etc/portage/make.conf: failed to source /etc/portage/make.conf.lto (/etc/portage/make.conf.lto: failed to source make.conf.lto.defines (cannot read file make.conf.lto.defines))
`

works if I manually `cd /etc/portage` before running eix-sync

I believe sourcing should be done with CWD set to wherever make.conf lives. I tried switching to absolute paths, but in this case the sourced file contains more relative sources, and the concern with switching them all to absolute paths is breaking compatibility with gentoo prefixes, etc.

**Comment by vaeth** [comment]
Sourcing relative filenames in make.conf does not make much sense since files can be directories.
Perhaps it makes sense in case of relative paths to prefix the path of the current file, although this might be rather strange this file resides in a recursively read subdirectory.
Do you know how portage handles it?

> the concern with switching them all to absolute paths is breaking compatibility with gentoo prefixes

Not sure how portage is handling it, but eix knows the variable EIXRC_SOURCE as a prefix for source commands within make.conf

**Comment by wolfwood** [comment]
EIXRC_SOURCE=/etc/portage isn't having the desired effect for me

paths are not relative in the sense of using ../ or having any directory component, its just that my make.conf uses `source make.conf.lto` which then sources `make.conf.lto.defines` and all the files are siblings in /etc/portage

**Comment by wolfwood** [comment]
I'm not sure how portage is handling it, other that to say that is seems to let us get away with it

**Comment by vaeth** [comment]
I added now the mentioned heuristics, though I am not sure it matches with portage's behaviour.

In any case, I would say the "correct" thing to do is not to use source with relative filenames but instead to turn /etc/portage/make.conf into a directory and put all required files there (or into subdirectories thereof). If you want to exclude certain files/dirs make them hidden (i.e. let their name start with ".").

**Comment by wolfwood** [comment]
thanks!
